//! User configuration (plan 020): 2-scope merge (global + local) with
//! per-field granular override.
//!
//! - Global: `~/.arlm/arlm.toml` — identity (`[auth]`), the user's AI
//!   (`[llm]`), and the target server (`[server] addr`).
//! - Local: `.arlm.toml` in the project root (gitignored, generated by
//!   `arlm init`) — per-project overrides and `[project]` metadata.
//!
//! Per-field merge rules:
//! - `[server]` and `[project]` merge recursively field-by-field; a local
//!   field wins, an absent local field falls back to the global value.
//! - `[llm]` is taken from the local scope when present, otherwise from the
//!   global scope (the whole backend list is overridden).
//! - `[auth]` is **global-only**: if a local `.arlm.toml` contains `[auth]` it
//!   is ignored entirely (the local file never carries credentials).
//!
//! Break total: the legacy `~/.arlm/config.toml` / `.arlm/config.toml` files
//! are NOT read. Only `~/.arlm/arlm.toml` and `.arlm.toml` are consulted.

use std::path::PathBuf;

use anyhow::{Context, Result};
use serde::Deserialize;

use arlm_llm::{BackendConfig, LlmConfig};

/// Auth section (global-only). Carries the user's refresh token minted by the
/// server admin (`arlm-server admin create-refresh`).
#[derive(Debug, Clone, Default, Deserialize)]
pub struct AuthConfig {
    /// Auditing username, mirrored from the created token.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,

    /// Refresh token (plaintext). Never sent except to `AuthRefresh`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub refresh_token: Option<String>,
}

/// Server connection section.
#[derive(Debug, Clone, Default, Deserialize)]
pub struct ServerSection {
    /// gRPC server address (e.g. `127.0.0.1:50051` or `https://host:443`).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub addr: Option<String>,
}

/// Project metadata section (local `.arlm.toml`).
#[derive(Debug, Clone, Default, Deserialize)]
pub struct ProjectSection {
    /// Human-readable project name.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,

    /// Glob ignore patterns seeded from `.gitignore`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ignore: Option<Vec<String>>,
}

/// Global config file shape (`~/.arlm/arlm.toml`).
#[derive(Debug, Clone, Default, Deserialize)]
struct GlobalConfig {
    auth: Option<AuthConfig>,
    llm: Option<LlmConfig>,
    server: Option<ServerSection>,
    project: Option<ProjectSection>,
}

/// Local config file shape (`.arlm.toml`). Note: a `[auth]` section in the
/// local file is intentionally **ignored** (serde skips unknown fields), so it
/// is simply absent from this struct — credentials stay global-only.
#[derive(Debug, Clone, Default, Deserialize)]
struct LocalConfig {
    llm: Option<LlmConfig>,
    server: Option<ServerSection>,
    project: Option<ProjectSection>,
}

/// The effective, merged user configuration used by the CLI.
#[derive(Debug, Clone, Default)]
pub struct EffectiveUserConfig {
    /// Global-only identity (always from `~/.arlm/arlm.toml`).
    pub auth: Option<AuthConfig>,
    /// Effective LLM backends (local override, else global).
    pub llm: Option<LlmConfig>,
    /// Effective server connection.
    pub server: ServerSection,
    /// Effective project metadata.
    pub project: ProjectSection,
}

impl EffectiveUserConfig {
    /// The server address to connect to: explicit `server.addr` (local over
    /// global), then the `ARLM_SERVER_ADDR` env var, then a localhost default.
    #[must_use]
    pub fn server_addr(&self) -> String {
        if let Some(addr) = self.server.addr.clone() {
            return addr;
        }
        if let Ok(addr) = std::env::var("ARLM_SERVER_ADDR") {
            return addr;
        }
        "127.0.0.1:50051".to_string()
    }

    /// The user's LLM backends, if any are configured.
    #[must_use]
    pub fn llm_config(&self) -> Option<&LlmConfig> {
        self.llm.as_ref()
    }

    /// The user's auth identity (global-only), if present.
    #[must_use]
    pub fn auth(&self) -> Option<&AuthConfig> {
        self.auth.as_ref()
    }

    /// Project ignore patterns (local over global), if any.
    #[must_use]
    pub fn ignore_patterns(&self) -> Vec<String> {
        self.project.ignore.clone().unwrap_or_default()
    }
}

/// Load and merge the global + local user configuration.
///
/// Missing files are treated as empty scopes (the merge then produces a
/// default [`EffectiveUserConfig`]); a malformed file is an error.
///
/// # Errors
///
/// Returns an error if either config file exists but cannot be parsed.
pub fn load() -> Result<EffectiveUserConfig> {
    let global = read_global()?;
    let local = read_local()?;

    // `[auth]` is global-only: ignore any local `auth`.
    let auth = global.auth;

    // `[llm]`: merge backends list-wise (local over global per backend) when
    // both scopes define it; otherwise take whichever is present.
    let llm = match (global.llm, local.llm) {
        (Some(g), Some(l)) => Some(LlmConfig {
            backends: merge_backends(&g.backends, &l.backends),
        }),
        (Some(g), None) => Some(g),
        (None, Some(l)) => Some(l),
        (None, None) => None,
    };

    // `[server]`: merge field-by-field (only `addr` for now).
    let server = ServerSection {
        addr: local
            .server
            .and_then(|s| s.addr)
            .or_else(|| global.server.and_then(|s| s.addr)),
    };

    // `[project]`: merge field-by-field.
    let local_project = local.project;
    let global_project = global.project;
    let project = ProjectSection {
        name: local_project
            .as_ref()
            .and_then(|p| p.name.clone())
            .or_else(|| global_project.as_ref().and_then(|p| p.name.clone())),
        ignore: local_project
            .as_ref()
            .and_then(|p| p.ignore.clone())
            .or_else(|| global_project.as_ref().and_then(|p| p.ignore.clone())),
    };

    Ok(EffectiveUserConfig {
        auth,
        llm,
        server,
        project,
    })
}

/// Merge two backend lists: local backends override global backends that share
/// the same logical name, and any purely-local backend is appended.
#[must_use]
pub fn merge_backends(global: &[BackendConfig], local: &[BackendConfig]) -> Vec<BackendConfig> {
    let mut out: Vec<BackendConfig> = Vec::with_capacity(global.len() + local.len());
    for g in global {
        match local.iter().find(|l| same_backend(l, g)) {
            Some(l) => out.push(l.clone()),
            None => out.push(g.clone()),
        }
    }
    for l in local {
        if !out.iter().any(|b| same_backend(b, l)) {
            out.push(l.clone());
        }
    }
    out
}

/// Two backends are "the same" when they share a name, a model, or a family.
fn same_backend(a: &BackendConfig, b: &BackendConfig) -> bool {
    if let (Some(an), Some(bn)) = (&a.name, &b.name) {
        return an == bn;
    }
    if let (Some(am), Some(bm)) = (&a.model, &b.model) {
        return am == bm;
    }
    a.family == b.family
}

fn global_path() -> PathBuf {
    home_dir().join(".arlm").join("arlm.toml")
}

fn local_path() -> PathBuf {
    std::env::current_dir()
        .unwrap_or_else(|_| PathBuf::from("."))
        .join(".arlm.toml")
}

fn read_global() -> Result<GlobalConfig> {
    let path = global_path();
    if !path.exists() {
        return Ok(GlobalConfig::default());
    }
    let content = std::fs::read_to_string(&path)
        .with_context(|| format!("failed to read {}", path.display()))?;
    let cfg: GlobalConfig =
        toml::from_str(&content).with_context(|| "failed to parse ~/.arlm/arlm.toml")?;
    Ok(cfg)
}

fn read_local() -> Result<LocalConfig> {
    let path = local_path();
    if !path.exists() {
        return Ok(LocalConfig::default());
    }
    let content = std::fs::read_to_string(&path)
        .with_context(|| format!("failed to read {}", path.display()))?;
    let cfg: LocalConfig =
        toml::from_str(&content).with_context(|| "failed to parse .arlm.toml")?;
    Ok(cfg)
}

fn home_dir() -> PathBuf {
    std::env::var("HOME")
        .ok()
        .map(PathBuf::from)
        .or_else(|| std::env::var("USERPROFILE").ok().map(PathBuf::from))
        .unwrap_or_else(|| PathBuf::from("."))
}
