//! User configuration (plan 020): 2-scope merge (global + local) with
//! per-field granular override.
//!
//! - Global: `~/.arags/arags.toml` — identity (`[auth]`), the user's AI
//!   (`[llm]`), and the target server (`[server] addr`).
//! - Local: `.arags.toml` in the project root (gitignored, generated by
//!   `arags init`) — per-project overrides and `[project]` metadata.
//!
//! Per-field merge rules:
//! - `[server]` and `[project]` merge recursively field-by-field; a local
//!   field wins, an absent local field falls back to the global value.
//! - `[llm]` is taken from the local scope when present, otherwise from the
//!   global scope (the whole backend list is overridden).
//! - `[auth]` is **global-only**: if a local `.arags.toml` contains `[auth]` it
//!   is ignored entirely (the local file never carries credentials).
//!
//! Break total: the legacy `~/.arags/config.toml` / `.arags/config.toml` files
//! are NOT read. Only `~/.arags/arags.toml` and `.arags.toml` are consulted.

use anyhow::{Result, bail};
use serde::Deserialize;

use arags_llm::LlmConfig;

/// Auth section (global-only). Carries the user's refresh token minted by the
/// server admin (`arags-server admin create-refresh`).
#[derive(Debug, Clone, Default, Deserialize)]
pub struct AuthConfig {
    /// Auditing username, mirrored from the created token.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,

    /// Refresh token (plaintext). Never sent except to `AuthRefresh`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub refresh_token: Option<String>,
}

/// Server connection section.
///
/// TLS fields (plan 020): `tls_ca` trusts a custom CA; `tls_cert`/`tls_key`
/// present a client certificate (mTLS, matching the server's `mtls_ca`).
#[derive(Debug, Clone, Default, Deserialize)]
pub struct ServerSection {
    /// gRPC server address (e.g. `127.0.0.1:50051` or `https://host:443`).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub addr: Option<String>,

    /// PEM CA bundle to trust instead of (or alongside) system roots.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tls_ca: Option<String>,

    /// PEM client certificate for mTLS.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tls_cert: Option<String>,

    /// PEM client private key for mTLS.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tls_key: Option<String>,
}

/// Project metadata section (local `.arags.toml`).
#[derive(Debug, Clone, Default, Deserialize)]
pub struct ProjectSection {
    /// Human-readable project name.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,

    /// Glob ignore patterns seeded from `.gitignore`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ignore: Option<Vec<String>>,
}

/// Watch registration (`[watch]` in the local `.arags.toml`), written by
/// `arags index --register`.
#[derive(Debug, Clone, Default, Deserialize)]
pub struct WatchSection {
    /// Whether background auto-update watching is enabled.
    #[serde(default)]
    pub enabled: bool,

    /// Project name under which chunks were indexed at registration time
    /// (keeps daemon re-uploads consistent with manual indexing).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub project: Option<String>,
}

/// Global config file shape (`~/.arags/arags.toml`).
#[derive(Debug, Clone, Default, Deserialize)]
pub struct GlobalConfig {
    auth: Option<AuthConfig>,
    llm: Option<LlmConfig>,
    server: Option<ServerSection>,
    project: Option<ProjectSection>,
    volunteer: Option<VolunteerConfig>,
}

/// Volunteer worker section (global-only): registers this client as an RLM
/// processing volunteer with its local LLM and resource quota.
#[derive(Debug, Clone, Deserialize)]
pub struct VolunteerConfig {
    /// Opt-in switch: volunteers only work when explicitly enabled.
    #[serde(default)]
    pub enabled: bool,

    /// Which `[[llm.backends]]` entry to use (name/family); default = first.
    #[serde(default)]
    pub backend: Option<String>,

    /// Model override; default = backend's configured model.
    #[serde(default)]
    pub model: Option<String>,

    /// Max completion tokens per synthesized summary.
    #[serde(default = "default_vol_max_tokens")]
    pub max_tokens_per_job: u32,

    /// Claimed-job lease in seconds (server honors it verbatim). Default
    /// 500s for every level per project decision.
    #[serde(default = "default_vol_lease_secs")]
    pub lease_secs: u64,

    /// Highest level this volunteer accepts (1=file, 2=theme, 3=project);
    /// 0/3 = any.
    #[serde(default = "default_vol_max_level")]
    pub max_level: u32,

    /// Seconds to sleep when the queue is empty.
    #[serde(default = "default_vol_poll_secs")]
    pub poll_secs: u64,
}

fn default_vol_max_tokens() -> u32 {
    2048
}
fn default_vol_lease_secs() -> u64 {
    500
}
fn default_vol_max_level() -> u32 {
    3
}
fn default_vol_poll_secs() -> u64 {
    30
}

impl Default for VolunteerConfig {
    fn default() -> Self {
        Self {
            enabled: false,
            backend: None,
            model: None,
            max_tokens_per_job: default_vol_max_tokens(),
            lease_secs: default_vol_lease_secs(),
            max_level: default_vol_max_level(),
            poll_secs: default_vol_poll_secs(),
        }
    }
}

/// Local config file shape (`.arags.toml`). Note: a `[auth]` section in the
/// local file is intentionally **ignored** (serde skips unknown fields), so it
/// is simply absent from this struct — credentials stay global-only.
#[derive(Debug, Clone, Default, Deserialize)]
pub struct LocalConfig {
    /// Merged LLM backends (local overrides global by backend name).
    pub llm: Option<LlmConfig>,
    pub server: Option<ServerSection>,
    pub project: Option<ProjectSection>,
    pub watch: Option<WatchSection>,
}

/// The effective, merged user configuration used by the CLI.
#[derive(Debug, Clone, Default)]
pub struct EffectiveUserConfig {
    /// Global-only identity (always from `~/.arags/arags.toml`).
    pub auth: Option<AuthConfig>,
    /// Effective LLM backends (local override, else global).
    pub llm: Option<LlmConfig>,
    /// Effective server connection.
    pub server: ServerSection,
    /// Effective project metadata.
    pub project: ProjectSection,
    /// Watch registration (local-only; never merged from global).
    pub watch: Option<WatchSection>,
    /// Volunteer registration (global-only; opt-in).
    pub volunteer: Option<VolunteerConfig>,
}

impl EffectiveUserConfig {
    /// Resolve the server address: explicit `server.addr` (local over
    /// global), then the `ARAGS_SERVER_ADDR` env override, then a localhost
    /// default.
    #[must_use]
    pub fn server_addr(&self) -> String {
        resolve_addr(
            self.server.addr.as_deref(),
            std::env::var("ARAGS_SERVER_ADDR").ok().as_deref(),
        )
    }

    /// The user's LLM backends, if any are configured.
    #[must_use]
    pub fn llm_config(&self) -> Option<&LlmConfig> {
        self.llm.as_ref()
    }

    /// The user's auth identity (global-only), if present.
    #[must_use]
    pub fn auth(&self) -> Option<&AuthConfig> {
        self.auth.as_ref()
    }

    /// Project ignore patterns (local over global), if any.
    #[must_use]
    pub fn ignore_patterns(&self) -> Vec<String> {
        self.project.ignore.clone().unwrap_or_default()
    }

    /// Effective index ignore patterns: the project `[project] ignore` list
    /// (local over global) merged with the `ARAGS_INDEX_IGNORE` env var
    /// (comma-separated). Defaults are applied at discovery time and can be
    /// extended here (issue agnostic-rlm-rs-a884).
    #[must_use]
    pub fn index_ignore_patterns(&self) -> Vec<String> {
        let mut out = self.ignore_patterns();
        if let Ok(env) = std::env::var("ARAGS_INDEX_IGNORE") {
            for p in env.split(',') {
                let p = p.trim().to_string();
                if !p.is_empty() && !out.contains(&p) {
                    out.push(p);
                }
            }
        }
        out
    }
}

/// A canonical project name is a **logical** identifier for the knowledge
/// entity, not a filesystem path (issue `agnostic-rlm-rs-f5db`). Worktrees of
/// the same repo share one canonical name; the on-disk root is tracked
/// separately by the server.
///
/// Valid names are non-empty and must not be a path: `.`, `..`, or an absolute
/// path (Unix `/…`, Windows `C:\…`). These are rejected because they are the
/// legacy buffer keys the issue forbids; a logical name keeps indexing
/// idempotent across worktrees.
#[must_use]
pub fn is_valid_canonical_name(name: &str) -> bool {
    if name.trim().is_empty() {
        return false;
    }
    if name == "." || name == ".." {
        return false;
    }
    // Reject absolute paths (legacy buffer keys). `Path::is_absolute` catches
    // both Unix (`/abs`) and Windows (`C:\abs`, `C:/abs`).
    if std::path::Path::new(name).is_absolute() {
        return false;
    }
    true
}

/// Resolve the canonical project name from the effective config.
///
/// # Errors
///
/// Returns an error if `[project].name` is unset (the operator must provide it
/// via `arags init --name`) or if it is set to an invalid legacy key (`.`,
/// `..`, or an absolute path).
pub fn resolve_canonical_name(cfg: &EffectiveUserConfig) -> Result<String> {
    match cfg.project.name.as_deref() {
        Some(name) if is_valid_canonical_name(name) => Ok(name.to_string()),
        Some(name) => bail!(
            "configured [project].name {name:?} is invalid: the canonical name must be a logical \
             identifier (e.g. `my-service`), not a filesystem path or `.`. Edit `.arags.toml` \
             and set a valid [project].name."
        ),
        None => bail!(
            "no canonical project name set. Run `arags init --name <NAME>` to define the \
             project's knowledge-entity name (required; not derived from the path)."
        ),
    }
}

/// Load and merge the global + local user configuration.
///
/// Missing files are treated as empty scopes (the merge then produces a
/// default [`EffectiveUserConfig`]); a malformed file is an error.
///
/// # Errors
///
/// Returns an error if either config file exists but cannot be parsed.
pub mod ops;
pub use ops::{
    load, load_from, load_local_at, merge, merge_backends, resolve_addr, set_watch_enabled,
};
