//! User configuration (plan 020): 2-scope merge (global + local) with
//! per-field granular override.
//!
//! - Global: `~/.arags/arags.toml` — identity (`[auth]`), the user's AI
//!   (`[llm]`), and the target server (`[server] addr`).
//! - Local: `.arags.toml` in the project root (gitignored, generated by
//!   `arags init`) — per-project overrides and `[project]` metadata.
//!
//! Per-field merge rules:
//! - `[server]` and `[project]` merge recursively field-by-field; a local
//!   field wins, an absent local field falls back to the global value.
//! - `[llm]` is taken from the local scope when present, otherwise from the
//!   global scope (the whole backend list is overridden).
//! - `[auth]` is **global-only**: if a local `.arags.toml` contains `[auth]` it
//!   is ignored entirely (the local file never carries credentials).
//!
//! Break total: the legacy `~/.arags/config.toml` / `.arags/config.toml` files
//! are NOT read. Only `~/.arags/arags.toml` and `.arags.toml` are consulted.

use std::path::PathBuf;

use anyhow::{Context, Result};
use serde::Deserialize;

use arags_llm::{BackendConfig, LlmConfig};

/// Auth section (global-only). Carries the user's refresh token minted by the
/// server admin (`arags-server admin create-refresh`).
#[derive(Debug, Clone, Default, Deserialize)]
pub struct AuthConfig {
    /// Auditing username, mirrored from the created token.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,

    /// Refresh token (plaintext). Never sent except to `AuthRefresh`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub refresh_token: Option<String>,
}

/// Server connection section.
///
/// TLS fields (plan 020): `tls_ca` trusts a custom CA; `tls_cert`/`tls_key`
/// present a client certificate (mTLS, matching the server's `mtls_ca`).
#[derive(Debug, Clone, Default, Deserialize)]
pub struct ServerSection {
    /// gRPC server address (e.g. `127.0.0.1:50051` or `https://host:443`).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub addr: Option<String>,

    /// PEM CA bundle to trust instead of (or alongside) system roots.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tls_ca: Option<String>,

    /// PEM client certificate for mTLS.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tls_cert: Option<String>,

    /// PEM client private key for mTLS.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tls_key: Option<String>,
}

/// Project metadata section (local `.arags.toml`).
#[derive(Debug, Clone, Default, Deserialize)]
pub struct ProjectSection {
    /// Human-readable project name.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,

    /// Glob ignore patterns seeded from `.gitignore`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ignore: Option<Vec<String>>,
}

/// Watch registration (`[watch]` in the local `.arags.toml`), written by
/// `arags index --register`.
#[derive(Debug, Clone, Default, Deserialize)]
pub struct WatchSection {
    /// Whether background auto-update watching is enabled.
    #[serde(default)]
    pub enabled: bool,

    /// Project name under which chunks were indexed at registration time
    /// (keeps daemon re-uploads consistent with manual indexing).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub project: Option<String>,
}

/// Global config file shape (`~/.arags/arags.toml`).
#[derive(Debug, Clone, Default, Deserialize)]
pub struct GlobalConfig {
    auth: Option<AuthConfig>,
    llm: Option<LlmConfig>,
    server: Option<ServerSection>,
    project: Option<ProjectSection>,
    volunteer: Option<VolunteerConfig>,
}

/// Volunteer worker section (global-only): registers this client as an RLM
/// processing volunteer with its local LLM and resource quota.
#[derive(Debug, Clone, Deserialize)]
pub struct VolunteerConfig {
    /// Opt-in switch: volunteers only work when explicitly enabled.
    #[serde(default)]
    pub enabled: bool,

    /// Which `[[llm.backends]]` entry to use (name/family); default = first.
    #[serde(default)]
    pub backend: Option<String>,

    /// Model override; default = backend's configured model.
    #[serde(default)]
    pub model: Option<String>,

    /// Max completion tokens per synthesized summary.
    #[serde(default = "default_vol_max_tokens")]
    pub max_tokens_per_job: u32,

    /// Claimed-job lease in seconds (server honors it verbatim). Default
    /// 500s for every level per project decision.
    #[serde(default = "default_vol_lease_secs")]
    pub lease_secs: u64,

    /// Highest level this volunteer accepts (1=file, 2=theme, 3=project);
    /// 0/3 = any.
    #[serde(default = "default_vol_max_level")]
    pub max_level: u32,

    /// Seconds to sleep when the queue is empty.
    #[serde(default = "default_vol_poll_secs")]
    pub poll_secs: u64,
}

fn default_vol_max_tokens() -> u32 {
    2048
}
fn default_vol_lease_secs() -> u64 {
    500
}
fn default_vol_max_level() -> u32 {
    3
}
fn default_vol_poll_secs() -> u64 {
    30
}

impl Default for VolunteerConfig {
    fn default() -> Self {
        Self {
            enabled: false,
            backend: None,
            model: None,
            max_tokens_per_job: default_vol_max_tokens(),
            lease_secs: default_vol_lease_secs(),
            max_level: default_vol_max_level(),
            poll_secs: default_vol_poll_secs(),
        }
    }
}

/// Local config file shape (`.arags.toml`). Note: a `[auth]` section in the
/// local file is intentionally **ignored** (serde skips unknown fields), so it
/// is simply absent from this struct — credentials stay global-only.
#[derive(Debug, Clone, Default, Deserialize)]
pub struct LocalConfig {
    pub(crate) llm: Option<LlmConfig>,
    server: Option<ServerSection>,
    pub(crate) project: Option<ProjectSection>,
    pub(crate) watch: Option<WatchSection>,
}

/// The effective, merged user configuration used by the CLI.
#[derive(Debug, Clone, Default)]
pub struct EffectiveUserConfig {
    /// Global-only identity (always from `~/.arags/arags.toml`).
    pub auth: Option<AuthConfig>,
    /// Effective LLM backends (local override, else global).
    pub llm: Option<LlmConfig>,
    /// Effective server connection.
    pub server: ServerSection,
    /// Effective project metadata.
    pub project: ProjectSection,
    /// Watch registration (local-only; never merged from global).
    pub watch: Option<WatchSection>,
    /// Volunteer registration (global-only; opt-in).
    pub volunteer: Option<VolunteerConfig>,
}

impl EffectiveUserConfig {
    /// Resolve the server address: explicit `server.addr` (local over
    /// global), then the `ARAGS_SERVER_ADDR` env override, then a localhost
    /// default.
    #[must_use]
    pub fn server_addr(&self) -> String {
        resolve_addr(
            self.server.addr.as_deref(),
            std::env::var("ARAGS_SERVER_ADDR").ok().as_deref(),
        )
    }

    /// The user's LLM backends, if any are configured.
    #[must_use]
    pub fn llm_config(&self) -> Option<&LlmConfig> {
        self.llm.as_ref()
    }

    /// The user's auth identity (global-only), if present.
    #[must_use]
    pub fn auth(&self) -> Option<&AuthConfig> {
        self.auth.as_ref()
    }

    /// Project ignore patterns (local over global), if any.
    #[must_use]
    pub fn ignore_patterns(&self) -> Vec<String> {
        self.project.ignore.clone().unwrap_or_default()
    }
}

/// Load and merge the global + local user configuration.
///
/// Missing files are treated as empty scopes (the merge then produces a
/// default [`EffectiveUserConfig`]); a malformed file is an error.
///
/// # Errors
///
/// Returns an error if either config file exists but cannot be parsed.
pub fn load() -> Result<EffectiveUserConfig> {
    load_from(&global_path(), &local_path())
}

/// Pure, testable core of [`load`]: merge an explicit global file with an
/// explicit local file (either may not exist).
///
/// # Errors
///
/// Returns an error if either file exists but cannot be parsed.
pub fn load_from(global: &std::path::Path, local: &std::path::Path) -> Result<EffectiveUserConfig> {
    let global = read_toml_file::<GlobalConfig>(global, "global arags.toml")?;
    let local = read_toml_file::<LocalConfig>(local, "local .arags.toml")?;
    Ok(merge(global, local))
}

/// Parse a local `.arags.toml` at an explicit path (missing file = default).
/// Used by the watch daemon, which runs detached with an unknown cwd.
///
/// # Errors
///
/// Returns an error if the file exists but cannot be parsed.
pub fn load_local_at(local: &std::path::Path) -> Result<LocalConfig> {
    read_toml_file::<LocalConfig>(local, "local .arags.toml")
}

/// Merge a parsed global scope with a parsed local scope (plan 020).
#[must_use]
pub fn merge(global: GlobalConfig, local: LocalConfig) -> EffectiveUserConfig {
    // `[auth]` is global-only: the local scope cannot even carry it
    // (`LocalConfig` has no `auth` field), so it always comes from global.
    let auth = global.auth;

    // `[llm]`: merge backends list-wise (local over global per backend) when
    // both scopes define it; otherwise take whichever is present.
    let llm = match (global.llm, local.llm) {
        (Some(g), Some(l)) => Some(LlmConfig {
            backends: merge_backends(&g.backends, &l.backends),
        }),
        (Some(g), None) => Some(g),
        (None, Some(l)) => Some(l),
        (None, None) => None,
    };

    // `[server]`: merge field-by-field (granular; local wins per field).
    let (local_server, global_server) = (local.server, global.server);
    let server = ServerSection {
        addr: local_server
            .as_ref()
            .and_then(|s| s.addr.clone())
            .or_else(|| global_server.as_ref().and_then(|s| s.addr.clone())),
        tls_ca: local_server
            .as_ref()
            .and_then(|s| s.tls_ca.clone())
            .or_else(|| global_server.as_ref().and_then(|s| s.tls_ca.clone())),
        tls_cert: local_server
            .as_ref()
            .and_then(|s| s.tls_cert.clone())
            .or_else(|| global_server.as_ref().and_then(|s| s.tls_cert.clone())),
        tls_key: local_server
            .as_ref()
            .and_then(|s| s.tls_key.clone())
            .or_else(|| global_server.as_ref().and_then(|s| s.tls_key.clone())),
    };

    // `[project]`: merge field-by-field.
    let local_project = local.project;
    let global_project = global.project;
    let project = ProjectSection {
        name: local_project
            .as_ref()
            .and_then(|p| p.name.clone())
            .or_else(|| global_project.as_ref().and_then(|p| p.name.clone())),
        ignore: local_project
            .as_ref()
            .and_then(|p| p.ignore.clone())
            .or_else(|| global_project.as_ref().and_then(|p| p.ignore.clone())),
    };

    // `[watch]` is local-only (registration is per-project).
    let watch = local.watch;

    // `[volunteer]` is global-only (opt-in identity of this machine's user).
    let volunteer = global.volunteer;

    EffectiveUserConfig {
        auth,
        llm,
        server,
        project,
        watch,
        volunteer,
    }
}

/// Persist `[watch]` in the local `.arags.toml`, preserving every other
/// existing field (round-trips through `toml::Value`).
///
/// # Errors
///
/// Fails on read/parse/write of the local config file.
pub fn set_watch_enabled(local: &std::path::Path, enabled: bool, project: &str) -> Result<()> {
    let mut doc: toml::Value = if local.exists() {
        let raw = std::fs::read_to_string(local)
            .with_context(|| format!("failed to read {}", local.display()))?;
        raw.parse()
            .with_context(|| format!("failed to parse {}", local.display()))?
    } else {
        toml::Value::Table(toml::map::Map::new())
    };
    let root = doc
        .as_table_mut()
        .context("local .arags.toml is not a TOML table")?;
    let mut watch = toml::map::Map::new();
    watch.insert("enabled".into(), toml::Value::Boolean(enabled));
    if enabled {
        watch.insert("project".into(), toml::Value::String(project.to_string()));
    }
    root.insert("watch".into(), toml::Value::Table(watch));
    let serialized =
        toml::to_string_pretty(&doc).context("failed to serialize local .arags.toml")?;
    std::fs::write(local, serialized)
        .with_context(|| format!("failed to write {}", local.display()))
}

/// Address precedence: configured `server.addr` first (local already won over
/// global in [`merge`]), then the `ARAGS_SERVER_ADDR` env override, then the
/// localhost default. Plan 020 keeps the env var working "as if set".
#[must_use]
fn resolve_addr(configured: Option<&str>, env: Option<&str>) -> String {
    const DEFAULT: &str = "127.0.0.1:50051";
    configured
        .or(env)
        .map_or(DEFAULT.to_string(), str::to_string)
}

/// Read + parse a TOML config file; a missing file is an empty default.
fn read_toml_file<T: serde::de::DeserializeOwned>(
    path: &std::path::Path,
    label: &str,
) -> Result<T> {
    if !path.exists() {
        // `Default` is only derived for the exact config structs.
        return toml::from_str("").with_context(|| format!("failed to parse empty {label}"));
    }
    let content = std::fs::read_to_string(path)
        .with_context(|| format!("failed to read {}", path.display()))?;
    toml::from_str(&content).with_context(|| format!("failed to parse {label}"))
}

/// Merge two backend lists: local backends override global backends that share
/// the same logical name, and any purely-local backend is appended.
#[must_use]
pub fn merge_backends(global: &[BackendConfig], local: &[BackendConfig]) -> Vec<BackendConfig> {
    let mut out: Vec<BackendConfig> = Vec::with_capacity(global.len() + local.len());
    for g in global {
        match local.iter().find(|l| same_backend(l, g)) {
            Some(l) => out.push(l.clone()),
            None => out.push(g.clone()),
        }
    }
    for l in local {
        if !out.iter().any(|b| same_backend(b, l)) {
            out.push(l.clone());
        }
    }
    out
}

/// Two backends are "the same" when they share a name, a model, or a family.
fn same_backend(a: &BackendConfig, b: &BackendConfig) -> bool {
    if let (Some(an), Some(bn)) = (&a.name, &b.name) {
        return an == bn;
    }
    if let (Some(am), Some(bm)) = (&a.model, &b.model) {
        return am == bm;
    }
    a.family == b.family
}

fn global_path() -> PathBuf {
    home_dir().join(".arags").join("arags.toml")
}

fn local_path() -> PathBuf {
    std::env::current_dir()
        .unwrap_or_else(|_| PathBuf::from("."))
        .join(".arags.toml")
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    fn write(path: &std::path::Path, content: &str) {
        std::fs::write(path, content).expect("test write");
    }

    const GLOBAL: &str = r#"
[auth]
username = "dev1"
refresh_token = "tok-123"

[llm]
[[llm.backends]]
name = "default"
family = "openai"
model = "gpt-4o-mini"
api_key = "sk-x"

[server]
addr = "https://arags.corp.internal:50051"

[project]
name = "global-name"
ignore = ["target/"]
"#;

    #[test]
    fn test_user_config_merge_local_overrides_global_granular() {
        let dir = TempDir::new().unwrap();
        let g = dir.path().join("global.toml");
        let l = dir.path().join("local.toml");
        write(&g, GLOBAL);
        // Only `addr` is overridden; everything else falls back to global.
        write(
            &l,
            "[server]\naddr = \"http://localhost:50051\"\n\n[project]\nignore = [\"dist/\"]\n",
        );

        let cfg = load_from(&g, &l).unwrap();
        assert_eq!(cfg.server_addr(), "http://localhost:50051");
        // Absent locally → falls back to the global value, granularly.
        assert_eq!(cfg.project.name.as_deref(), Some("global-name"));
        assert_eq!(cfg.ignore_patterns(), vec!["dist/".to_string()]);
    }

    #[test]
    fn test_user_config_nested_merge_recursive() {
        let dir = TempDir::new().unwrap();
        let g = dir.path().join("global.toml");
        let l = dir.path().join("local.toml");
        write(
            &g,
            "[llm]\n[[llm.backends]]\nname = \"default\"\nfamily = \"openai\"\nmodel = \"gpt-4o-mini\"\n\n[[llm.backends]]\nname = \"spare\"\nfamily = \"ollama\"\nbase_url = \"http://localhost:11434\"\n",
        );
        // Local redefines only the `default` backend (by name); `spare` from
        // global survives the merge.
        write(
            &l,
            "[llm]\n[[llm.backends]]\nname = \"default\"\nfamily = \"ollama\"\nmodel = \"qwen2.5-coder:7b\"\n",
        );

        let cfg = load_from(&g, &l).unwrap();
        let llm = cfg.llm_config().unwrap();
        assert_eq!(llm.backends.len(), 2);
        assert_eq!(llm.backends[0].family.to_string().to_lowercase(), "ollama");
        assert_eq!(llm.backends[0].model.as_deref(), Some("qwen2.5-coder:7b"));
        assert_eq!(llm.backends[1].name.as_deref(), Some("spare"));
    }

    #[test]
    fn test_auth_only_global() {
        let dir = TempDir::new().unwrap();
        let g = dir.path().join("global.toml");
        let l = dir.path().join("local.toml");
        write(&g, GLOBAL);
        // A local `[auth]` must be ignored entirely (no credentials in repo).
        write(
            &l,
            "[auth]\nusername = \"evil\"\nrefresh_token = \"stolen\"\n",
        );

        let cfg = load_from(&g, &l).unwrap();
        let auth = cfg.auth().unwrap();
        assert_eq!(auth.username.as_deref(), Some("dev1"));
        assert_eq!(auth.refresh_token.as_deref(), Some("tok-123"));
    }

    #[test]
    fn test_legacy_config_toml_ignored() {
        let dir = TempDir::new().unwrap();
        // Legacy-named files are present but MUST NOT be read (plan 020 D4):
        // `load_from` is only ever pointed at arags.toml / .arags.toml.
        let legacy = dir.path().join("config.toml");
        write(
            &legacy,
            "[auth]\nusername = \"old\"\nrefresh_token = \"legacy\"\n\n[server]\naddr = \"legacy:1\"\n",
        );
        // Pointing at the *new* names (which do not exist) yields defaults —
        // the legacy file content never leaks into the effective config.
        let cfg = load_from(
            &dir.path().join("arags.toml"),
            &dir.path().join(".arags.toml"),
        )
        .unwrap();
        assert!(cfg.server.addr.is_none());
        assert!(cfg.auth.is_none());
    }

    #[test]
    fn test_client_uses_merged_server_addr_and_env_override() {
        // Pure precedence: config > env > default.
        assert_eq!(resolve_addr(Some("cfg:1"), None), "cfg:1");
        assert_eq!(resolve_addr(None, Some("env:2")), "env:2");
        assert_eq!(resolve_addr(Some("cfg:1"), Some("env:2")), "cfg:1");
        assert_eq!(resolve_addr(None, None), "127.0.0.1:50051");
    }

    #[test]
    fn test_missing_files_default() {
        let dir = TempDir::new().unwrap();
        let cfg = load_from(&dir.path().join("none.toml"), &dir.path().join("none.toml")).unwrap();
        assert!(cfg.auth.is_none());
        assert!(cfg.llm.is_none());
        assert_eq!(cfg.project.name, None);
    }

    #[test]
    fn test_server_tls_fields_merge_granularly() {
        let dir = TempDir::new().unwrap();
        let g = dir.path().join("global.toml");
        let l = dir.path().join("local.toml");
        write(
            &g,
            "[server]\naddr = \"https://a:1\"\ntls_ca = \"/etc/arags/ca.crt\"\ntls_cert = \"/etc/arags/client.crt\"\ntls_key = \"/etc/arags/client.key\"\n",
        );
        // Local overrides only `addr`; TLS knobs fall back to global.
        write(&l, "[server]\naddr = \"http://localhost:50051\"\n");

        let cfg = load_from(&g, &l).unwrap();
        assert_eq!(cfg.server_addr(), "http://localhost:50051");
        assert_eq!(cfg.server.tls_ca.as_deref(), Some("/etc/arags/ca.crt"));
        assert_eq!(
            cfg.server.tls_cert.as_deref(),
            Some("/etc/arags/client.crt")
        );
        assert_eq!(cfg.server.tls_key.as_deref(), Some("/etc/arags/client.key"));
    }

    #[test]
    fn test_malformed_local_file_is_error() {
        let dir = TempDir::new().unwrap();
        let g = dir.path().join("global.toml");
        let l = dir.path().join("local.toml");
        write(&g, GLOBAL);
        write(&l, "not [ valid toml ===");
        assert!(load_from(&g, &l).is_err());
    }
}

fn home_dir() -> PathBuf {
    std::env::var("HOME")
        .ok()
        .map(PathBuf::from)
        .or_else(|| std::env::var("USERPROFILE").ok().map(PathBuf::from))
        .unwrap_or_else(|| PathBuf::from("."))
}

#[cfg(test)]
mod disjoint_tests {
    use super::*;
    use tempfile::TempDir;

    /// Plan 020: `server.toml` (data plane) and the user config are disjoint
    /// files. A `server.toml`-shaped file parsed as **user** config must not
    /// leak any of its data-plane values into the effective user config.
    #[test]
    fn test_user_config_ignores_server_toml_semantics() {
        let dir = TempDir::new().unwrap();
        // Full server.toml shape (plan 020 schema).
        let server_toml = r#"
listen_addr = "0.0.0.0:50051"
data_dir = "/var/lib/arags"
pool_size = 4
flush_interval_ms = 100
max_batch_size = 50

[embedder]
max_tokens = 512
overlap_tokens = 64

[search]
tier = "hybrid"

[history]
retention_days = 90
"#;
        let path = dir.path().join("server.toml");
        std::fs::write(&path, server_toml).unwrap();

        let cfg = load_from(&path, &dir.path().join(".arags.toml")).unwrap();
        // None of the data-plane keys map onto user config sections.
        assert!(cfg.auth.is_none());
        assert!(cfg.llm.is_none());
        assert!(
            cfg.server.addr.is_none(),
            "listen_addr must NOT become [server].addr"
        );
        assert_eq!(cfg.server.tls_ca, None);
        assert_eq!(cfg.project.name, None);
        assert_eq!(cfg.server_addr(), "127.0.0.1:50051");
    }
}

#[cfg(test)]
mod watch_tests {
    #![allow(clippy::unwrap_used, clippy::expect_used)]

    use super::*;

    #[test]
    fn test_set_watch_enabled_roundtrip_preserves_fields() {
        let dir = tempfile::TempDir::new().unwrap();
        let path = dir.path().join(".arags.toml");
        std::fs::write(
            &path,
            "[project]\nname = \"demo\"\nignore = [\"target/\"]\n\n[server]\naddr = \"10.0.0.5:50051\"\n",
        )
        .unwrap();

        set_watch_enabled(&path, true, "demo").unwrap();
        let raw = std::fs::read_to_string(&path).unwrap();
        assert!(raw.contains("[project]"));
        assert!(raw.contains("[server]"));
        assert!(raw.contains("enabled = true"));

        let local = load_local_at(&path).unwrap();
        assert!(local.watch.as_ref().is_some_and(|w| w.enabled));
        assert_eq!(local.watch.and_then(|w| w.project).as_deref(), Some("demo"));
        assert_eq!(
            local.project.as_ref().and_then(|p| p.name.as_deref()),
            Some("demo")
        );

        // Unregister clears the flag but keeps the section and other data.
        set_watch_enabled(&path, false, "").unwrap();
        let local = load_local_at(&path).unwrap();
        assert!(!local.watch.unwrap().enabled);
    }

    #[test]
    fn test_set_watch_enabled_creates_missing_file() {
        let dir = tempfile::TempDir::new().unwrap();
        let path = dir.path().join(".arags.toml");
        set_watch_enabled(&path, true, "p").unwrap();
        let local = load_local_at(&path).unwrap();
        assert!(local.watch.is_some_and(|w| w.enabled));
    }
}
